// <auto-generated />
namespace EntityFramwork_FluentApi_and_DataAnotations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddShopAdress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShopAdress));
        
        string IMigrationMetadata.Id
        {
            get { return "201712250905229_AddShop.Adress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
